name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm64:latest

    steps:
    - uses: actions/checkout@v4
    - name: libnx
      run: |
        git clone --recursive https://github.com/switchbrew/libnx.git
        cd libnx
        make install
        sudo make install
    - name: make 
      run: |
        aarch64-none-elf-cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake 
        mkdir nxout; for i in *; do for j in "$i".nro; cp -r "$j" nxout; done;

    - name: upload
      uses: actions/upload-artifact@v4
      with: 
        path: nxout
