name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v4
    - name: libnx
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITA64=/opt/devkitpro/devkitA64
        git clone --recursive https://github.com/switchbrew/libnx.git
        cd libnx
        make install

    - name: make 
      run: |
        git config --global --add safe.directory /__w/dolphin-switch/dolphin-switch
        apt install ssh
        git submodule add git@github.com:arsenm/sanitizers-cmake.git externals/sanitizers-cmake
        git submodule add git@github.com:fmtlib/fmt.git externals/fmt
        chmod +x aarch64-none-elf-cmake
        ./aarch64-none-elf-cmake -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake 
        mkdir nxout; for i in *; do for j in "$i".nro; do cp -r "$j" nxout; done; done;

    - name: upload
      uses: actions/upload-artifact@v4
      with: 
        path: nxout
